export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT'
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_STATUS = 'CART_SAVE_PAYMENT_STATUS'

export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'