//-----All constants related to order------

// Creating a new order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

//request for order details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

// order payment
export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS'
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

// update order status
export const ORDER_STATUS_REQUEST = 'ORDER_STATUS_REQUEST'
export const ORDER_STATUS_SUCCESS = 'ORDER_STATUS_SUCCESS'
export const ORDER_STATUS_FAIL = 'ORDER_STATUS_FAIL'
export const ORDER_STATUS_RESET = 'ORDER_STATUS_RESET'


// orders for specific user
export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL'
export const MY_ORDER_LIST_RESET = 'MY_ORDER_LIST_RESET'


// all orders
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'


