// all constants related to payment

// Creating a new payment
export const PAYMENT_CREATE_REQUEST = 'PAYMENT_CREATE_REQUEST'
export const PAYMENT_CREATE_SUCCESS = 'PAYMENT_CREATE_SUCCESS'
export const PAYMENT_CREATE_FAIL = 'PAYMENT_CREATE_FAIL'

export const PAYMENT_CREATE_RESET = 'PAYMENT_CREATE_RESET'

export const PAYMENT_UPDATE_REQUEST = 'PAYMENT_UPDATE_REQUEST'
export const PAYMENT_UPDATE_SUCCESS = 'PAYMENT_UPDATE_SUCCESS'
export const PAYMENT_UPDATE_FAIL = 'PAYMENT_UPDATE_FAIL'

export const PAYMENT_UPDATE_RESET = 'PAYMENT_UPDATE_RESET'