export const REPORT_TOTALS_REQUEST = 'REPORT_TOTALS_REQUEST'
export const REPORT_TOTALS_SUCCESS = 'REPORT_TOTALS_SUCCESS'
export const REPORT_TOTALS_FAIL = 'REPORT_TOTALS_FAIL'

export const REPORT_CATEGORY_REQUEST = 'REPORT_CATEGORY_REQUEST'
export const REPORT_CATEGORY_SUCCESS = 'REPORT_CATEGORY_SUCCESS'
export const REPORT_CATEGORY_FAIL = 'REPORT_CATEGORY_FAIL'