# Generated by Django 3.2.6 on 2021-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderStatus',
        ),
        migrations.AddField(
            model_name='order',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
