# Generated by Django 3.2.6 on 2021-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210928_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('CR', 'Placed'), ('PK', 'Packaged'), ('SH', 'Shipped Out'), ('RC', 'Received')], default='CR', max_length=2),
        ),
    ]
