# Generated by Django 3.2.6 on 2021-09-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lastUpdatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
