# Generated by Django 3.2.6 on 2021-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_lastupdatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Packaged', 'Packaged'), ('Shipped Out', 'Shipped Out'), ('Received', 'Received')], default='Placed', max_length=20),
        ),
    ]
