# Generated by Django 3.2.6 on 2021-10-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
    ]
