# Generated by Django 3.2.6 on 2021-10-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_user_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
