# Generated by Django 3.2.6 on 2021-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_user_id_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Packaged', 'Packaged'), ('Shipped', 'Shipped Out'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
