# Generated by Django 3.2.6 on 2021-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_image3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image3D',
            field=models.ImageField(blank=True, null=True, upload_to='images/3DModels'),
        ),
    ]
