# Generated by Django 3.2.6 on 2021-10-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_image3d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image3D',
            new_name='model3D',
        ),
    ]
