# Generated by Django 3.2.6 on 2021-11-02 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20211027_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastUpdatedAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
