# Generated by Django 3.1.4 on 2021-11-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20211105_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
