# Generated by Django 3.1.4 on 2021-11-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amountPaid',
        ),
        migrations.AddField(
            model_name='payment',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
