# Generated by Django 3.2.6 on 2021-12-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='base.category'),
        ),
    ]
